if(!require("shiny")) install.packages("shiny",dependencies=T)
if(!require("ggplot2")) install.packages("ggplot2",dependencies=T)
if(!require("reshape2")) install.packages("reshape2",dependencies=T)
if(!require("gplots")) install.packages("gplots",dependencies=T)
if(!require("pheatmap")) install.packages("pheatmap",dependencies=T)
if(!require("scatterD3")) install.packages("scatterD3",dependencies=T)
if(!require("DT")) install.packages("DT",dependencies=T)
if(!require("mclust")) install.packages("mclust",dependencies=T)
if(!require("tsne")) install.packages("tsne",dependencies=T)
if(!require("devtools")) install.packages("devtools",dependencies=T)
if(!require("png")) install.packages("png",dependencies=T)
devtools::install_github("zji90/SCRAT")
